// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Projeto1_IF.Models;

[Table("tbContrato")]
[Index("IdPlano", Name = "IX_tbContrato_IdPlano")]
public partial class TbContrato
{
    [Key]
    public int IdContrato { get; set; }

    public int IdPlano { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? DataInicio { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? DataFim { get; set; }

    [ForeignKey("IdPlano")]
    [InverseProperty("TbContratos")]
    public virtual TbPlano IdPlanoNavigation { get; set; }

    [InverseProperty("IdContratoNavigation")]
    public virtual ICollection<TbProfissional> TbProfissionals { get; set; } = new List<TbProfissional>();
}